name: azure_openai
description: Dart package for Azure Open AI Service
version: 0.0.1
repository: https://github.com/tyler-jewell/azure_openai
issue_tracker: https://github.com/tyler-jewell/azure_openai/issues

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^6.0.0
